image:
  repository: docker.n8n.io/n8nio/n8n
  tag: "2.15.0"
  pullPolicy: IfNotPresent

multiMain:
  enabled: true
  replicas: 2

queueMode:
  workerReplicaCount: 2
  workerConcurrency: 20

webhookProcessor:
  enabled: true
  replicaCount: 1
  disableProductionWebhooksOnMainProcess: true

ingress:
  enabled: false

networkPolicy:
  enabled: false

secretRefs:
  existingSecret: n8n-app-secrets

resources:
  main:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
  worker:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
  webhookProcessor:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi


s3:
  enabled: false
  storage:
    mode: s3
    availableModes: s3
