database:
  type: postgresdb
  useExternal: true
  host: <POSTGRES_HOST>
  port: 5432
  database: <POSTGRES_DBNAME>
  ssl:
    enabled: true
    rejectUnauthorized: false
  passwordSecret:
    name: n8n-db-secret
    key: password

redis:
  enabled: true
  useExternal: true
  host: <REDIS_HOST>
  port: 6379
  tls: true
  passwordSecret:
    name: n8n-redis-secret
    key: password
