fullnameOverride: n8n-fi

webhook:
  enabled: true
  url: https://fi.ea58fe1.kyma.ondemand.com

database:
  host: postgres-93fb7fe0-0a3b-4e6f-aa61-ec6e16af85ae.cwqnonr4r4q7.eu-central-1.rds.amazonaws.com
  port: 2504
  database: aTCIeNwDNZcG
  user: n8n_fi_user
  schema: n8n_fi
  ssl:
    enabled: true
    rejectUnauthorized: false

redis:
  host: master.cm-148e4000-1165-4b3f-82f8-1596cb0f56b4.tg302k.euc1.cache.amazonaws.com
  port: 6379
  prefix: n8n-fi
  tls: true

taskRunners:
  image:
    repository: ghcr.io/fakhry000/n8n-fi-task-runner
    tag: "2.15.0"
    pullPolicy: IfNotPresent

config:
  extraEnv:
    - name: N8N_EDITOR_BASE_URL
      value: https://fi.ea58fe1.kyma.ondemand.com
    - name: WEBHOOK_URL
      value: https://fi.ea58fe1.kyma.ondemand.com