apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-fi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: n8n-platform
  sources:
    - repoURL: ghcr.io/n8n-io/n8n-helm-chart
      chart: n8n
      targetRevision: 1.3.0
      helm:
        releaseName: n8n-fi
        valueFiles:
          - $values/clean-kyma/config/common/n8n-common.yaml
          - $values/clean-kyma/config/instances/n8n-fi.yaml
    - repoURL: https://github.com/fakhry000/acc-kyma.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-fi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
