apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-hr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: n8n-platform
  sources:
    - repoURL: https://github.com/n8n-io/n8n-hosting.git
      targetRevision: v1.2.0
      path: charts/n8n
      helm:
        releaseName: n8n-hr
        valueFiles:
          - $values/config/common/n8n-common.yaml
          - $values/config/common/platform-shared.yaml
          - $values/config/instances/n8n-hr.yaml
    - repoURL: https://github.com/fakhry000/acc-kyma.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-hr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
