apiVersion: v1
kind: Secret
metadata:
  name: n8n-app-secrets
  namespace: n8n-fi
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: CHANGE_ME_FI_ENCRYPTION_KEY
  N8N_HOST: fi.ea58fe1.kyma.ondemand.com
  N8N_PORT: "5678"
  N8N_PROTOCOL: https
