apiVersion: v1
kind: Secret
metadata:
  name: n8n-db-secret
  namespace: n8n-fi
type: Opaque
stringData:
  username: n8n_fi_user
  password: CHANGE_ME_FI_DB_PASSWORD
  hostname: <POSTGRES_HOST>
  port: "5432"
  dbname: <POSTGRES_DBNAME>
  schema: n8n-fi
