apiVersion: v1
kind: Secret
metadata:
  name: n8n-app-secrets
  namespace: n8n-hr
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: CHANGE_ME_HR_ENCRYPTION_KEY
  N8N_HOST: hr.<YOUR_KYMA_DOMAIN>
  N8N_PORT: "5678"
  N8N_PROTOCOL: https
  N8N_SMTP_USER: CHANGE_ME_SMTP_USER
  N8N_SMTP_PASS: CHANGE_ME_SMTP_PASSWORD
