name: build-task-runners

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'images/runners/**'
      - '.github/workflows/build-task-runners.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        instance: [hr, fi]
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: images/runners/${{ matrix.instance }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/n8n-${{ matrix.instance }}-task-runner:2.15.0
